version: '3.8'
services:
  ai-classifier:
    build: .
    volumes:
      - .:/usr/src/app
      - data_volume:/usr/src/app/data
    ports:
      - "5000:80"
    environment:
      - DEBUG=1

volumes:
  data_volume:
