[build]
  command = "python -m venv venv && . venv/bin/activate && pip install -r requirements.txt && python app.py"
  publish = "/"
  functions = "functions/"

[build.environment]
  PYTHON_VERSION = "3.8"
  PIP_VERSION = "latest"