[build]
  command = "C:\\Users\\hoang\\AppData\\Local\\Programs\\Python\\Python312\\python.exe -m pip install -r requirements.txt && C:\\Users\\hoang\\AppData\\Local\\Programs\\Python\\Python312\\python.exe app.py"
  publish = "/"
  functions = "functions/"

[build.environment]
  PYTHON_VERSION = "3.12"
  PIP_VERSION = "latest"
